print results from parallel jobs

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -65,6 +65,15 @@ jobs:
     steps:
       - run: |
           set -ex
-          echo '${{ toJSON(needs.verify.outputs) }}'
+          echo '${{ toJSON(needs.verify.outputs) }}' \
+          | jq -j 'to_entries[] | select(.key | startswith("failed_libraries_")) | .value' \
+          | sed 's/,/\n/g > failed_libs
+
+          if [[ $(cat failed_libs | wc -l) -gt 0 ]]; then
+            echo "The following libraries have failures:"
+            cat failed_libs
+            exit 1
+          fi
+          echo "All libraries of the current variant are compilable!"
 
 
