parallelize by alphabet letter

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -13,8 +13,11 @@ jobs:
     runs-on: 'ubuntu-24.04'
     strategy:
       matrix:
-        variant: [ 1.26.0, 1.27.0, 1.28.0, 1.29.2, 1.30.1, 1.31.0, 2.0.0 ]
-      fail-fast: false
+        # We will parallelize by alphabet letter
+        ascii_code: ${{ range(97, 102) }}
+        fail-fast: false
+    outputs:
+      failed_libraries:
     steps:
       - uses: actions/setup-java@v3
         with:
@@ -26,5 +29,13 @@ jobs:
 
       - working-directory: google-api-java-client-services
         run: |
-          bash .github/workflows/verify.sh ${{ matrix.variant }}
+          set -ex
+          bash .github/workflows/verify.sh "$(printf "\x$(printf %x ${{ matrix.ascii_code }})")"
+  print_results:
+    needs: [verify]
+    steps:
+      - run: |
+          set -ex
+          echo '${{ toJSON(needs.verify.failed_libraries) }}'
+
 
